### ISSUE TITLE
Mobs make weird pauses to recalculate(?) 

### ISSUE THREAD

**Issue by nekorii04** [zapzombies/zap-community#43] opened 2021-09-30 15:42 UTC
**Describe the bug**
t for title !

**Where did the bug occur**
map nt

**To Reproduce**
1. play
2. go to whatever round maybe r30

**Expected behavior**
they're supposed to walk normally

**Screenshots**
https://user-images.githubusercontent.com/90960152/135487417-8bfbd6ae-24d5-49e4-b9d3-d1e16e258c21.mp4

**Additional context**
I don't know if this is because of godmode/fly or something

**Comment by nekorii04** [comment] 2021-09-30 15:42
https://user-images.githubusercontent.com/90960152/135487513-c1bb607a-ce86-4d0b-918d-60513bba7535.mp4

**Comment by Steanky** [comment] 2021-10-01 12:31
Possibly fixed on cleanup- I went to r30 myself (after applying fixes) and was unable to reproduce this issue

**Comment by Steanky** [comment] 2021-10-01 12:51
@nekorii04 re-open this if it's still a problem rather than making a new issue

**Closed by Steanky** 2021-10-01 12:51 UTC
Labels: bug
